name: myrentapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20
  video_player: ^2.8.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  flutterfire_cli: ^0.1.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcomepage.png
    - assets/signup_bg.png
    - assets/login.png
    - assets/splash.mp4
    - assets/profile_avatar.png
    - assets/bg.png


    #firebase App Id 1:701491757967:android:8c27f5b5f84fc6631c41fa